"""
Category analytics route handlers.
Provides category revenue contributions, time-series trends, details, comparison, top/bottom performers, and CSV exports.
"""

import logging
import csv
import io
from datetime import datetime, date, timezone
from typing import List, Dict, Any, Optional
from fastapi import APIRouter, Depends, Query, HTTPException, Response, status
from pydantic import BaseModel, Field
from sqlalchemy.orm import Session
from sqlalchemy import func

from database import get_db
from auth import get_current_user
from dashboard.filters.date_filters import resolve_date_range
from dashboard.services import category_service
from services.sale_return_service import POSTED_SALE_STATUSES
import models

# ── Logger Setup ──────────────────────────────────────────────────────────────
logger = logging.getLogger("smartvyapar.categories")
logger.setLevel(logging.INFO)

router = APIRouter()

ALLOWED_PRESETS = {"today", "yesterday", "this_week", "last_week", "this_month", "last_month", "last7", "last30", "this_year", "custom"}


# ── Pydantic Schemas ──────────────────────────────────────────────────────────
class CategoryContributionItem(BaseModel):
    category_id: Optional[int] = Field(None, description="Category database ID")
    category_name: str = Field(..., description="Category name")
    total_revenue: float = Field(0.0, description="Total gross revenue generated by category")
    percentage: float = Field(0.0, description="Revenue contribution percentage of total")
    total_qty_sold: float = Field(0.0, description="Total quantity of items sold in category")


class CategoryTrendSeries(BaseModel):
    category_name: str = Field(..., description="Category name")
    data: List[float] = Field(default_factory=list, description="Revenue data points over time")


class CategoryTrendResponse(BaseModel):
    labels: List[str] = Field(default_factory=list, description="Time labels (days or months)")
    series: List[CategoryTrendSeries] = Field(default_factory=list, description="Series per category")


class CategoryListItem(BaseModel):
    id: int
    name: str
    description: Optional[str] = None
    product_count: int = 0


class CategoryListResponse(BaseModel):
    categories: List[CategoryListItem]
    count: int


class CategoryDetailsResponse(BaseModel):
    category_id: int
    category_name: str
    period_start: str
    period_end: str
    total_revenue: float
    contribution_percentage: float
    total_qty_sold: float
    product_count: int
    top_product_name: Optional[str] = None


class CategoryComparisonItem(BaseModel):
    category_id: Optional[int]
    category_name: str
    revenue: float
    contribution_pct: float
    order_items_count: int


class CategoryComparisonResponse(BaseModel):
    period_start: str
    period_end: str
    total_category_revenue: float
    categories: List[CategoryComparisonItem]


class TopBottomCategoryResponse(BaseModel):
    top_categories: List[CategoryContributionItem]
    bottom_categories: List[CategoryContributionItem]


class HealthCheckResponse(BaseModel):
    status: str
    module: str
    timestamp: str


# ── Helper Functions ──────────────────────────────────────────────────────────
def _validate_date_inputs(preset: Optional[str], start_date: Optional[str], end_date: Optional[str]):
    if preset and preset.lower() not in ALLOWED_PRESETS:
        raise HTTPException(
            status_code=status.HTTP_422_UNPROCESSABLE_ENTITY,
            detail=f"Invalid preset '{preset}'. Allowed presets: {', '.join(sorted(ALLOWED_PRESETS))}"
        )
    if start_date and isinstance(start_date, str):
        try:
            date.fromisoformat(start_date)
        except (ValueError, TypeError):
            raise HTTPException(
                status_code=status.HTTP_422_UNPROCESSABLE_ENTITY,
                detail=f"Invalid start_date '{start_date}'. Must be YYYY-MM-DD format."
            )
    if end_date and isinstance(end_date, str):
        try:
            date.fromisoformat(end_date)
        except (ValueError, TypeError):
            raise HTTPException(
                status_code=status.HTTP_422_UNPROCESSABLE_ENTITY,
                detail=f"Invalid end_date '{end_date}'. Must be YYYY-MM-DD format."
            )


# ── Endpoints ─────────────────────────────────────────────────────────────────

@router.get("/health", response_model=HealthCheckResponse, summary="Categories module health check")
def categories_health():
    """Health check endpoint for the categories module."""
    return HealthCheckResponse(
        status="ok",
        module="categories",
        timestamp=datetime.now(timezone.utc).isoformat()
    )


@router.get("/contributions", response_model=List[CategoryContributionItem], summary="Get revenue contribution by category")
def category_contributions(
    preset: Optional[str] = Query(None, description="Date preset filter: this_month, last30, etc."),
    start_date: Optional[str] = Query(None, description="Start date YYYY-MM-DD"),
    end_date: Optional[str] = Query(None, description="End date YYYY-MM-DD"),
    category_name: Optional[str] = Query(None, description="Filter by specific category name"),
    db: Session = Depends(get_db),
    current_user: models.User = Depends(get_current_user),
):
    """
    Retrieves revenue contribution and quantity sold grouped by product category.
    Fully preserves payload array format expected by desktop UI.
    """
    try:
        _validate_date_inputs(preset, start_date, end_date)
        start, end = resolve_date_range(start_date, end_date, preset or "this_month")
        logger.info(f"[Categories] User '{current_user.username}' requested contributions for period {start} to {end}")
        
        raw = category_service.get_category_contributions(db, start, end)
        
        if category_name:
            c_lower = category_name.lower().strip()
            raw = [c for c in raw if c_lower in str(c.get("category_name", "")).lower()]

        items = [CategoryContributionItem(**item) for item in raw]
        return items
    except HTTPException:
        raise
    except Exception as e:
        logger.error(f"[Categories Error] Failed to calculate category contributions: {e}", exc_info=True)
        raise HTTPException(
            status_code=status.HTTP_500_INTERNAL_SERVER_ERROR,
            detail=f"Error calculating category contributions: {str(e)}"
        )


@router.get("/trend", summary="Get category revenue trend time-series")
def category_trend(
    preset: Optional[str] = Query(None),
    start_date: Optional[str] = Query(None),
    end_date: Optional[str] = Query(None),
    top_n: int = Query(5, ge=2, le=10, description="Top N categories to chart"),
    db: Session = Depends(get_db),
    current_user: models.User = Depends(get_current_user),
):
    """Retrieves revenue trend time-series for the top N performing categories."""
    try:
        _validate_date_inputs(preset, start_date, end_date)
        start, end = resolve_date_range(start_date, end_date, preset or "this_year")
        logger.info(f"[Categories] User '{current_user.username}' requested trend for period {start} to {end} (top_n={top_n})")
        
        trend_data = category_service.get_category_trend_series(db, start, end, top_n)
        return trend_data
    except HTTPException:
        raise
    except Exception as e:
        logger.error(f"[Categories Error] Failed to generate category trend: {e}", exc_info=True)
        raise HTTPException(
            status_code=status.HTTP_500_INTERNAL_SERVER_ERROR,
            detail=f"Error calculating category trend: {str(e)}"
        )


@router.get("/list", response_model=CategoryListResponse, summary="List all product categories")
def list_categories(
    query: Optional[str] = Query(None, description="Search by category name"),
    limit: int = Query(100, ge=1, le=1000, description="Pagination limit"),
    offset: int = Query(0, ge=0, description="Pagination offset"),
    db: Session = Depends(get_db),
    current_user: models.User = Depends(get_current_user),
):
    """Lists all product categories with product count metrics."""
    try:
        logger.info(f"[Categories] User '{current_user.username}' requested category list")
        q = db.query(models.Category)
        
        if query:
            q = q.filter(models.Category.name.ilike(f"%{query.strip()}%"))

        total_count = q.count()
        cats = q.order_by(models.Category.name.asc()).offset(offset).limit(limit).all()

        items = []
        for c in cats:
            p_count = db.query(models.Product).filter(models.Product.category_id == c.id, models.Product.is_active == 1).count()
            items.append(CategoryListItem(
                id=c.id,
                name=c.name,
                description=c.description,
                product_count=p_count
            ))

        return CategoryListResponse(categories=items, count=total_count)
    except Exception as e:
        logger.error(f"[Categories Error] Failed to list categories: {e}", exc_info=True)
        raise HTTPException(
            status_code=status.HTTP_500_INTERNAL_SERVER_ERROR,
            detail=f"Error fetching categories list: {str(e)}"
        )


@router.get("/details/{category_id}", response_model=CategoryDetailsResponse, summary="Get details for single category")
def get_category_details(
    category_id: int,
    preset: Optional[str] = Query(None),
    start_date: Optional[str] = Query(None),
    end_date: Optional[str] = Query(None),
    db: Session = Depends(get_db),
    current_user: models.User = Depends(get_current_user),
):
    """Retrieves detailed performance metrics for a specific product category."""
    try:
        _validate_date_inputs(preset, start_date, end_date)
        start, end = resolve_date_range(start_date, end_date, preset or "this_month")
        
        cat = db.query(models.Category).filter(models.Category.id == category_id).first()
        if not cat:
            raise HTTPException(status_code=status.HTTP_404_NOT_FOUND, detail=f"Category ID {category_id} not found")

        raw_contribs = category_service.get_category_contributions(db, start, end)
        target = next((c for c in raw_contribs if c.get("category_id") == category_id), None)
        
        total_rev = target.get("total_revenue", 0.0) if target else 0.0
        pct = target.get("percentage", 0.0) if target else 0.0
        qty = target.get("total_qty_sold", 0.0) if target else 0.0

        p_count = db.query(models.Product).filter(models.Product.category_id == category_id, models.Product.is_active == 1).count()
        
        # Find top selling product in category
        sold_rows = db.query(
            models.Product.id,
            models.Product.name,
            func.sum(models.SaleItem.qty).label("qty"),
        ).join(models.SaleItem).join(models.Sale).filter(
            models.Product.category_id == category_id,
            models.Sale.status.in_(POSTED_SALE_STATUSES),
            func.date(models.Sale.created_at) >= start,
            func.date(models.Sale.created_at) <= end,
        ).group_by(models.Product.id, models.Product.name).all()
        returned_rows = db.query(
            models.SaleReturnItem.product_id,
            func.sum(models.SaleReturnItem.qty).label("qty"),
        ).join(models.SaleReturn).join(
            models.Product, models.Product.id == models.SaleReturnItem.product_id
        ).filter(
            models.Product.category_id == category_id,
            func.date(models.SaleReturn.posted_at) >= start,
            func.date(models.SaleReturn.posted_at) <= end,
        ).group_by(models.SaleReturnItem.product_id).all()
        returned_map = {row.product_id: float(row.qty or 0) for row in returned_rows}
        top_prod = max(
            sold_rows,
            key=lambda row: float(row.qty or 0) - returned_map.get(row.id, 0.0),
            default=None,
        )
        top_p_name = top_prod.name if top_prod else None

        return CategoryDetailsResponse(
            category_id=cat.id,
            category_name=cat.name,
            period_start=start,
            period_end=end,
            total_revenue=total_rev,
            contribution_percentage=pct,
            total_qty_sold=qty,
            product_count=p_count,
            top_product_name=top_p_name
        )
    except HTTPException:
        raise
    except Exception as e:
        logger.error(f"[Categories Error] Failed to get category details for ID {category_id}: {e}", exc_info=True)
        raise HTTPException(
            status_code=status.HTTP_500_INTERNAL_SERVER_ERROR,
            detail=f"Error getting category details: {str(e)}"
        )


@router.get("/top-bottom", response_model=TopBottomCategoryResponse, summary="Get top and bottom performing categories")
def top_bottom_categories(
    preset: Optional[str] = Query(None),
    start_date: Optional[str] = Query(None),
    end_date: Optional[str] = Query(None),
    top_n: int = Query(5, ge=1, le=20),
    db: Session = Depends(get_db),
    current_user: models.User = Depends(get_current_user),
):
    """Returns top N and bottom N performing categories by revenue contribution."""
    try:
        _validate_date_inputs(preset, start_date, end_date)
        start, end = resolve_date_range(start_date, end_date, preset or "this_month")
        
        raw_contribs = category_service.get_category_contributions(db, start, end)
        sorted_contribs = sorted(raw_contribs, key=lambda x: x.get("total_revenue", 0.0), reverse=True)

        top_items = [CategoryContributionItem(**item) for item in sorted_contribs[:top_n]]
        bottom_items = [CategoryContributionItem(**item) for item in sorted_contribs[-top_n:]]

        return TopBottomCategoryResponse(
            top_categories=top_items,
            bottom_categories=bottom_items
        )
    except HTTPException:
        raise
    except Exception as e:
        logger.error(f"[Categories Error] Failed to calculate top/bottom categories: {e}", exc_info=True)
        raise HTTPException(
            status_code=status.HTTP_500_INTERNAL_SERVER_ERROR,
            detail=f"Error calculating top/bottom categories: {str(e)}"
        )


@router.get("/export", summary="Export category performance report as CSV")
def export_category_report(
    preset: Optional[str] = Query(None),
    start_date: Optional[str] = Query(None),
    end_date: Optional[str] = Query(None),
    db: Session = Depends(get_db),
    current_user: models.User = Depends(get_current_user),
):
    """Generates and downloads a CSV export of category revenue contributions."""
    try:
        _validate_date_inputs(preset, start_date, end_date)
        start, end = resolve_date_range(start_date, end_date, preset or "this_month")
        
        raw_contribs = category_service.get_category_contributions(db, start, end)

        output = io.StringIO()
        writer = csv.writer(output)
        
        # Write CSV Header
        writer.writerow(["Category ID", "Category Name", "Total Revenue (PKR)", "Contribution %", "Total Quantity Sold"])
        
        for c in raw_contribs:
            writer.writerow([
                c.get("category_id", ""),
                c.get("category_name", ""),
                f"{c.get('total_revenue', 0.0):.2f}",
                f"{c.get('percentage', 0.0):.1f}%",
                f"{c.get('total_qty_sold', 0.0):.2f}"
            ])

        output.seek(0)
        filename = f"category_performance_{start}_to_{end}.csv"
        
        return Response(
            content=output.getvalue(),
            media_type="text/csv",
            headers={"Content-Disposition": f"attachment; filename={filename}"}
        )
    except HTTPException:
        raise
    except Exception as e:
        logger.error(f"[Categories Error] Failed to export CSV: {e}", exc_info=True)
        raise HTTPException(
            status_code=status.HTTP_500_INTERNAL_SERVER_ERROR,
            detail=f"Error exporting category report CSV: {str(e)}"
        )
